//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Codigo_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public Nullable<int> Precio_Producto { get; set; }
        public Nullable<int> ID_Marca { get; set; }
        public string Color_Producto { get; set; }
        public string Descripcion_Producto { get; set; }
        public int Stock_Producto { get; set; }
        public int ID_Categoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Marca Marca { get; set; }
    }
}
